name: Tag new version

on:
  push:
    branches:
      - main

jobs:
  tag_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current version
        id: get_version
        run: |
          VERSION=$(sed -nE 's/^VERSION\s*=\s*"([0-9]+\.[0-9]+\.[0-9]+)".*/\1/p' config.py)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get latest tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          LATEST_VERSION=${LATEST_TAG#v}
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Compare versions and create new tag
        if: env.VERSION != env.LATEST_TAG
        run: |
          NEW_TAG="v$VERSION"
          git tag $NEW_TAG
          git push origin $NEW_TAG